// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eraqiltuojepbwsbbiqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVyYXFpbHR1b2plcGJ3c2JiaXFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NDQ5MDAsImV4cCI6MjA2NTAyMDkwMH0.ne6yceC7EhN0QomK4i8F5yxHKZMV2oX6oZsYvIxYwqM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);